#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_MESSMYPHOTO                         107
#define IDI_SMALL                               108
#define IDC_MESSMYPHOTO                         109
#define IDD_DIALOG1                             110
#define IDD_DIALOG2                             111
#define IDD_DIALOG3                             112
#define IDC_SLIDER4                             1002
#define IDC_RADIO1                              1006
#define IDC_RADIO2                              1007
#define IDC_RADIO3                              1008
#define IDM_DOG1                                40000
#define IDS_APP_TITLE                           40000
#define IDM_BILATERAL_FILTER1                   40001
#define IDM_OPEN_PHOTO1                         40002
#define IDM_PAINTERLY1                          40003
#define IDM_GRAYSCALE1                          40004
#define IDM_BLACK_N_WHITE1                      40005
#define IDM_ROTATE_LEFT1                        40006
#define IDM_CYBORG1                             40007
#define IDM_OLD_PHOTO1                          40008
#define IDM_ROTATE_RIGHT1                       40009
#define IDM_INVERT_COLORS1                      40010
#define IDM_NIGHT_VISION1                       40011
#define IDM_THERMAL_DETECTOR1                   40012
#define IDM_HONEYMOON1                          40013
#define IDM_SUN_BURST1                          40014
#define IDM_PATRONIZE1                          40015
#define IDM_STENCIL_ART1                        40016
#define IDM_MOTION_BLUR1                        40017
#define IDM_VINTAGE1                            40018
#define IDM_INKIFY1                             40019
#define IDM_GOLD_ENGROSS1                       40020
#define IDM_JIGSAW1                             40021
#define IDM_REFLECTION1                         40022
#define IDM_BARCODE1                            40023
#define IDM_HDR1                                40024
#define IDM_FISHEYE_LENS1                       40025
#define IDM_CROSS_PROCESS1                      40026
#define IDM_CYAN_TYPE1                          40027
#define IDM_HOLGAART1                           40028
#define IDM_TIE_AND_DYE1                        40029
#define IDM_WATER_COLOR1                        40030
#define IDM_OIL_PAINTING1                       40031
#define IDM_PERFECT_SKETCH1                     40032
#define IDM_MOTHER_NATURE1                      40033
